# Generated by Django 4.2.9 on 2024-02-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import metrics.models.page
import metrics.models.site
import metrics.models.snapshot


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the site",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug uniquely identifying the Site",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The site's homepage", verbose_name="URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description of the Site",
                        verbose_name="Description",
                    ),
                ),
                (
                    "sitemap_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to the site's sitemap",
                        verbose_name="Sitemap URL",
                    ),
                ),
                (
                    "sitemap_file",
                    models.FileField(
                        blank=True,
                        help_text="A file containing the sitemap for the Site",
                        null=True,
                        upload_to=metrics.models.site.sitemap_path,
                        verbose_name="Sitemap file",
                    ),
                ),
                (
                    "config_file",
                    models.FileField(
                        blank=True,
                        help_text="A JSON file containing command-line arguments for running Lighthouse",
                        null=True,
                        upload_to=metrics.models.site.config_path,
                        verbose_name="Config file",
                    ),
                ),
                (
                    "crontab",
                    models.CharField(
                        blank=True,
                        help_text="Crontab entry which defines the time a Snapshot will be taken",
                        max_length=100,
                        validators=[metrics.models.site.validate_crontab],
                        verbose_name="Crontab",
                    ),
                ),
                (
                    "snapped",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the last Snapshot was taken",
                        null=True,
                        verbose_name="Snapped",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        help_text="Is the site active", verbose_name="Enabled"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        help_text="The PDF report for the site metrics",
                        null=True,
                        upload_to=metrics.models.snapshot.report_path,
                        verbose_name="Report",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Parameters for creating snapshots and Page summary metrics",
                        verbose_name="Data",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The Site this Snapshot was created from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="metrics.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot",
                "verbose_name_plural": "Snapshots",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL of the page from the Site",
                        verbose_name="URL",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="A summary of the audit data for this Page",
                        verbose_name="Data",
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        help_text="The Lighthouse audit report for this Page",
                        null=True,
                        upload_to=metrics.models.page.audit_report_path,
                        verbose_name="Report",
                    ),
                ),
                (
                    "audited",
                    models.BooleanField(
                        help_text="The page was audited successfully, with no errors or warnings reported",
                        verbose_name="Audited",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        help_text="The Snapshot that this Page belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="metrics.snapshot",
                        verbose_name="Snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
    ]
