# Generated by Django 4.2.9 on 2024-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="config_file",
        ),
        migrations.AddField(
            model_name="site",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text="The command-line arguments for running Lighthouse in JSON format",
                verbose_name="Config",
            ),
        ),
    ]
