x-app: &default-app
  build:
    context: "."
    target: "app"
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
  depends_on:
    redis:
      condition: "service_started"
      required: false
  environment:
    DJANGO_ENV: ${DJANGO_ENV}
    DJANGO_DEBUG: ${DJANGO_DEBUG}
    DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    CRICKET_API_KEY: ${CRICKET_API_KEY}
  init: true
  restart: "unless-stopped"
  tty: true

services:
  redis:
    image: "redis:7.2"
    restart: "unless-stopped"
    volumes:
      - "redisdata:/data"

  django:
    <<: *default-app
    healthcheck:
      test: "curl localhost:8000/watchman/ping"
      interval: "60s"
      timeout: "3s"
      start_period: "30s"
      retries: 3
    volumes:
      - "data:/app/data"
      - "media:/app/media"
      - "static:/app/static"

  celery-beat:
    <<: *default-app
    command: celery -A config beat --loglevel "${CELERY_LOG_LEVEL:-debug}"
    depends_on:
      django:
        condition: "service_started"
        required: false
    entrypoint: null

  celery-worker:
    <<: *default-app
    command: celery -A config worker --loglevel "${CELERY_LOG_LEVEL:-debug}" -Q sites,pages
    depends_on:
      django:
        condition: "service_started"
        required: false
    entrypoint: null
    volumes:
      - "data:/app/data"
      - "media:/app/media"

volumes:
  data:
    {}
  redisdata:
    {}
  media:
    {}
  static:
    {}
