#
# Makefile: Commands to simplify development and releases
#
# Usage:
#
#    make sync
#    make checks
#    make tests

# This Makefile only works with GNU Make.

# Where everything lives
root_dir := $(realpath .)
src_dir = $(root_dir)/project

django = uv run python $(root_dir)/manage.py
flake8 = uv run flake8
ruff = uv run ruff
isort = uv run isort
mypy = uv run mypy
pytest = uv run pytest
coverage = uv run coverage

# include additional targets or override variables from local makefiles
-include *.mk

.PHONY: help
help:
	@echo "The Makefile has the following targets..."
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'

# #########
#   Clean
# #########
#
# Delete all the runtime files generated by the various targets.

.PHONY: clean-tests
clean-tests:
	@echo "Deleting the pytest cache..."
	rm -rf .pytest_cache

.PHONY: clean-mypy
clean-mypy:
	@echo "Deleting the mypy cache..."
	rm -rf .mypy_cache

.PHONY: clean-coverage
clean-coverage:
	@echo "Deleting the coverage data and reports..."
	rm -rf .coverage
	rm -rf coverage

.PHONY: clean
clean: clean-coverage clean-mypy clean-tests

# ##############
#   Virtualenv
# ##############
#
# Sync the virtualenv with the lockfile. Run this after pulling changes
# or whenever pyproject.toml is updated.

.PHONY: sync
sync:
	@echo "Sync the virtualenv..."
	uv sync --group dev

.PHONY: lock
lock:
	@echo "Update the lockfile..."
	uv lock

# ##########
#   Django
# ##########

.PHONY: migrate
migrate:
	@echo "Run any database migrations..."
	$(django) migrate

.PHONY: run
run: migrate
	@echo "Run Gunicorn web server..."
	uv run gunicorn -c config/gunicorn.py config.wsgi

# ##########
#   Checks
# ##########

.PHONY: flake8
flake8:
	@echo "Check the code for flake8 violations..."
	$(flake8) $(src_dir)

.PHONY: isort
isort:
	@echo "Check the code for import sort order violations..."
	$(isort) --check $(src_dir)

.PHONY: black
black:
	@echo "Check the code for formatting rules violations..."
	$(ruff) format --check $(src_dir)

.PHONY: mypy
mypy:
	@echo "Check the type annotations..."
	$(mypy) $(src_dir)

.PHONY: checks
checks: flake8 black isort mypy
	@echo "Run all the code checks..."

# #########
#   Tests
# #########

.PHONY: coverage
coverage:
	@echo "Generate test coverage report..."
	$(pytest) --cov=$(src_dir) --cov-report html

.PHONY: tests
tests:
	@echo "Run all the tests..."
	$(pytest)
