# Generated by Django 6.0.5 on 2026-06-06 16:31

import audits.models.job
import audits.models.report
import django.db.models.deletion
from django.db import migrations, models


def add_audits(apps, schema_editor):
    Audit = apps.get_model("audits", "Audit")

    Audit.objects.create(
        name="Page Headers",
        slug="page-headers",
        task="audits.tasks.page_headers",
        description="The page headers.",
    )
    Audit.objects.create(
        name="Page Weights",
        slug="page-weights",
        task="audits.tasks.page_weights",
        description="The page weights.",
    )

    Audit.objects.create(
        name="Performance",
        slug="performance",
        task="audits.tasks.lighthouse_audit",
        description="Lighthouse Performance Audit",
    )

    Audit.objects.create(
        name="SEO",
        slug="seo",
        task="audits.tasks.lighthouse_audit",
        description="Lighthouse SEO Audit",
    )

    Audit.objects.create(
        name="Accessibility",
        slug="accessibility",
        task="audits.tasks.lighthouse_audit",
        description="Lighthouse Accessibility Audit",
    )

    Audit.objects.create(
        name="Best Practices",
        slug="best-practices",
        task="audits.tasks.lighthouse_audit",
        description="Lighthouse Best Practices Audit",
    )


def remove_audits(apps, schema_editor):
    Audit = apps.get_model("audits", "Audit")
    Audit.objects.get(name="Page Headers").delete()
    Audit.objects.get(name="Page Weights").delete()


# Lighthouse Performance score is a weighted sum of these five metrics.
# Weights are from Lighthouse 12.x and are expressed as percentages (sum = 100).
_LIGHTHOUSE_PERFORMANCE_DEFINITIONS = [
    {
        "slug": "first-contentful-paint",
        "name": "First Contentful Paint",
        "weight": 10,
        "description": (
            "First Contentful Paint marks the time at which the first text or image "
            "is painted. A fast FCP reassures the user that the page is loading."
        ),
    },
    {
        "slug": "speed-index",
        "name": "Speed Index",
        "weight": 10,
        "description": (
            "Speed Index shows how quickly the contents of a page are visibly "
            "populated. A lower score means content appears sooner."
        ),
    },
    {
        "slug": "largest-contentful-paint",
        "name": "Largest Contentful Paint",
        "weight": 25,
        "description": (
            "Largest Contentful Paint marks the time at which the largest text or "
            "image is painted. A fast LCP means the page appears useful sooner."
        ),
    },
    {
        "slug": "total-blocking-time",
        "name": "Total Blocking Time",
        "weight": 30,
        "description": (
            "Sum of all time periods between FCP and Time to Interactive during "
            "which the main thread was blocked long enough to prevent input response, "
            "expressed in milliseconds."
        ),
    },
    {
        "slug": "cumulative-layout-shift",
        "name": "Cumulative Layout Shift",
        "weight": 25,
        "description": (
            "Cumulative Layout Shift measures the movement of visible elements "
            "within the viewport. A low CLS score means the page is visually stable."
        ),
    },
]


def add_definitions(apps, schema_editor):
    Audit = apps.get_model("audits", "Audit")
    Definition = apps.get_model("audits", "Definition")
    performance = Audit.objects.get(slug="performance")
    for defn in _LIGHTHOUSE_PERFORMANCE_DEFINITIONS:
        Definition.objects.create(audit=performance, **defn)


def remove_definitions(apps, schema_editor):
    Definition = apps.get_model("audits", "Definition")
    slugs = [d["slug"] for d in _LIGHTHOUSE_PERFORMANCE_DEFINITIONS]
    Definition.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Audit.', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='The slug used to refer to the Audit in API URLs.', max_length=100, unique=True, verbose_name='Slug')),
                ('task', models.CharField(help_text='The module path of the Celery task that performs the audit.', max_length=255, verbose_name='Task')),
                ('description', models.TextField(blank=True, help_text='An agent-friendly description of the Audit.', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL for the page', max_length=2000, unique=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the site.', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Used in API URLs. Auto-generated from name if left blank.', max_length=100, unique=True, verbose_name='Slug')),
                ('url', models.URLField(help_text="The site's main URL.", verbose_name='URL')),
                ('environment', models.CharField(blank=True, choices=[('local', 'Local'), ('staging', 'Staging'), ('production', 'Production')], help_text='The type of server environment. Used for filtering job runs.', max_length=20, verbose_name='Environment')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Definition.', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='The slug used to refer to the Definition in API URLs.', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='An agent-friendly description of the Definition.', verbose_name='Description')),
                ('weight', models.FloatField(blank=True, help_text='How much does the metric influence the overall score of the audit.', null=True, verbose_name='Weight')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
                ('audit', models.ForeignKey(help_text='The Audit that produces this Definition.', on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='audits.audit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the job.', max_length=100, verbose_name='Name')),
                ('sitemaps', models.TextField(blank=True, help_text='Optional. A newline-separated list of sitemaps to load.', verbose_name='Sitemaps')),
                ('urls', models.TextField(blank=True, help_text='Optional. A newline-separated list of page URLs to audit.', verbose_name='URLs')),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', help_text='The device to emulate when running an audit.', max_length=10, verbose_name='Device')),
                ('schedule', models.CharField(blank=True, help_text='Optional. A crontab schedule for running the job.', max_length=100, validators=[audits.models.job.validate_crontab], verbose_name='Schedule')),
                ('enabled', models.BooleanField(default=True, help_text='Is the job active?', verbose_name='Enabled')),
                ('description', models.TextField(blank=True, help_text='A description of the job. Add any additional detail to distinguish between jobs for the same site.', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
                ('executed', models.DateTimeField(blank=True, help_text='The date and time this job was last executed. Updated automatically.', null=True, verbose_name='Last run')),
                ('audits', models.ManyToManyField(help_text='The audits to perform on each page from the site.', to='audits.audit', verbose_name='Audits')),
                ('site', models.ForeignKey(help_text='The site to be audited.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_jobs', to='audits.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_report', models.FileField(blank=True, help_text='Audit results in JSON format.', null=True, upload_to=audits.models.report.audit_report_path, verbose_name='Report')),
                ('html_report', models.FileField(blank=True, help_text='Audit results in HTML format.', null=True, upload_to=audits.models.report.audit_report_path, verbose_name='HTML Report')),
                ('data', models.JSONField(default=dict, help_text='The raw data from running the audit.', verbose_name='Data')),
                ('error', models.TextField(blank=True, help_text='A description, or stack trace for any errors.', verbose_name='Error')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time the record was last modified.', verbose_name='Modified at')),
                ('audit', models.ForeignKey(help_text='The Audit that generated this Report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audits.audit', verbose_name='Audit')),
                ('page', models.ForeignKey(help_text='The Page that was audited to generate this Report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audits.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SlugField(help_text="A slug identifying the category of finding, e.g. 'dead-link', 'large-image'.", max_length=100, verbose_name='Type')),
                ('title', models.CharField(help_text='A short description of the finding.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Additional detail about the finding.', verbose_name='Description')),
                ('url', models.URLField(blank=True, help_text='The specific resource or URL this finding refers to, if applicable.', max_length=2000, verbose_name='URL')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', help_text='The severity of the finding.', max_length=10, verbose_name='Severity')),
                ('source', models.CharField(blank=True, help_text='The tool or agent that generated this finding.', max_length=255, verbose_name='Source')),
                ('data', models.JSONField(blank=True, help_text='Additional structured data for this finding.', null=True, verbose_name='Data')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('page', models.ForeignKey(help_text='The Page this Finding relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.page', verbose_name='Page')),
                ('report', models.ForeignKey(help_text='The Report this Finding was extracted from.', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='running', help_text='The current status of this Run.', max_length=10, verbose_name='Status')),
                ('page_count', models.IntegerField(blank=True, help_text='The number of pages audited.', null=True, verbose_name='Page count')),
                ('total_tasks', models.IntegerField(default=0, help_text='The number of audit-page tasks dispatched for this Run.', verbose_name='Total tasks')),
                ('completed_tasks', models.IntegerField(default=0, help_text='The number of audit-page tasks that have finished.', verbose_name='Completed tasks')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('job', models.ForeignKey(help_text='The Job that generated this Run.', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='audits.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='run',
            field=models.ForeignKey(help_text='The Run that generated this Report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audits.run', verbose_name='Run'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(help_text='The site for this page.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='audits.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured', models.DateTimeField(db_index=True, help_text="When the audit ran. Mirrors the Run's created timestamp.", verbose_name='Measured')),
                ('score', models.IntegerField(blank=True, help_text='The score for the metric.', null=True, verbose_name='Score')),
                ('rating', models.CharField(blank=True, choices=[('poor', 'Poor'), ('needs-improvement', 'Needs Improvement'), ('good', 'Good')], help_text='A rating for the metric.', max_length=20, null=True, verbose_name='Rating')),
                ('value', models.FloatField(blank=True, help_text='The actual value.', null=True, verbose_name='Value')),
                ('units', models.CharField(blank=True, help_text='The units for the value, e.g. milliseconds, bytes, etc.', max_length=50, verbose_name='Units')),
                ('data', models.JSONField(blank=True, help_text='The raw audit data used to generate this Metric.', null=True, verbose_name='Data')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was added.', verbose_name='Created at')),
                ('definition', models.ForeignKey(help_text='The Definition that describes this Metric.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='audits.definition', verbose_name='Definition')),
                ('page', models.ForeignKey(help_text='The Page this Metric was measured for.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='audits.page', verbose_name='Page')),
                ('report', models.ForeignKey(help_text='The Report from which this Metric was extracted.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='audits.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'indexes': [models.Index(fields=['definition', 'rating'], name='ck_metric_defn_rating_idx'), models.Index(fields=['page', 'definition', 'measured'], name='ck_metric_pg_defn_time_idx')],
            },
        ),
        migrations.RunPython(add_audits, remove_audits),
        migrations.RunPython(add_definitions, remove_definitions),
    ]
