from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views import generic

from metrics.models import Page, Rating, Snapshot


class PageListView(generic.ListView):
    template_name = "metrics/page/list.html"
    model = Page
    paginate_by = 50

    def get_snapshot(self):
        if not hasattr(self, "_snapshot"):
            self._snapshot = get_object_or_404(Snapshot, pk=self.kwargs["pk"])
        return self._snapshot

    def get_filters(self):
        filters = {"snapshot": self.get_snapshot()}

        rating = self.request.GET.get("rating")
        category = self.request.GET.get("category")
        audit = self.request.GET.get("audit")

        if category and rating:
            filters[
                "data__categories__{}__rating".format(category)
            ] = Rating.SLUGS.index(rating)
        elif audit and rating:
            filters["data__audits__{}__score".format(audit)] = Rating.SLUGS.index(
                rating
            )

        return filters

    def get_queryset(self):
        return self.model.objects.filter(**self.get_filters())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["snapshot"] = self.get_snapshot()
        return context


class PageDetailView(generic.DetailView):
    template_name = "metrics/page/detail.html"
    queryset = Page.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.object.data)
        context["category_order"] = [
            "performance",
            "accessibility",
            "best-practices",
            "seo",
        ]
        return context


class PageReportView(generic.DetailView):
    """Serve the self-contained Lighthouse HTML report for a single page.

    The report is generated by Lighthouse with ``--output html`` and stored as
    a file field on the Page.  Because Lighthouse inlines all CSS and
    JavaScript the file is completely self-contained and can be served
    directly — no template is required.
    """

    queryset = Page.objects.all()

    def get(self, request, *args, **kwargs):
        page = self.get_object()
        if not page.html_report:
            raise Http404("No HTML report is available for this page.")
        with page.html_report.open() as fp:
            content = fp.read()
        return HttpResponse(content, content_type="text/html; charset=utf-8")
