# Generated by Django 6.0.5 on 2026-06-06 16:31

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label for this key.', max_length=100, unique=True, verbose_name='Name')),
                ('key', models.CharField(default=api.models._generate_key, max_length=64, unique=True, verbose_name='Key')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last used')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, help_text='Limit this key to a single site; leave blank for all sites.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='audits.site', verbose_name='Site scope')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
    ]
