# Generated by Django 6.0.5 on 2026-06-02 18:41

import django.db.models.deletion
import django_extensions.db.fields
import sites.models.base_job
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url_source', models.CharField(choices=[('sitemap_url', 'Sitemap URL'), ('sitemap_file', 'Sitemap file'), ('url_list', 'URL list')], default='sitemap_url', max_length=20, verbose_name='URL source')),
                ('url_value', models.TextField(blank=True, help_text='Sitemap URL, or newline-separated list of URLs when source is "URL list". Leave blank when using an uploaded sitemap file.', verbose_name='URL value')),
                ('sitemap_file', models.FileField(blank=True, help_text="Uploaded sitemap XML. Only used when source is 'Sitemap file'.", null=True, upload_to=sites.models.base_job.sitemap_path, verbose_name='Sitemap file')),
                ('environment', models.CharField(blank=True, choices=[('local', 'Local'), ('staging', 'Staging'), ('production', 'Production')], help_text='Where this Job runs — tags all Runs for filtering.', max_length=20, verbose_name='Environment')),
                ('crontab', models.CharField(blank=True, help_text='Cron schedule, e.g. "0 9 * * 1" for Monday at 09:00. Leave blank for manual-only Jobs.', max_length=100, validators=[sites.models.base_job.validate_crontab], verbose_name='Crontab')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('last_run', models.DateTimeField(blank=True, help_text='Updated automatically when a Run is created.', null=True, verbose_name='Last run')),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10, verbose_name='Device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_jobs', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Page Weight Job',
                'verbose_name_plural': 'Page Weight Jobs',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Page count')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pageweight.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('final_url', models.URLField(blank=True, max_length=2000, verbose_name='Final URL')),
                ('measured', models.BooleanField(default=False, verbose_name='Measured')),
                ('total_transfer_size', models.BigIntegerField(default=0, verbose_name='Total transfer size (bytes)')),
                ('total_resource_size', models.BigIntegerField(default=0, verbose_name='Total resource size (bytes)')),
                ('resource_count', models.IntegerField(default=0, verbose_name='Resource count')),
                ('document_transfer', models.BigIntegerField(default=0)),
                ('stylesheet_transfer', models.BigIntegerField(default=0)),
                ('script_transfer', models.BigIntegerField(default=0)),
                ('image_transfer', models.BigIntegerField(default=0)),
                ('font_transfer', models.BigIntegerField(default=0)),
                ('other_transfer', models.BigIntegerField(default=0)),
                ('document_size', models.BigIntegerField(default=0)),
                ('stylesheet_size', models.BigIntegerField(default=0)),
                ('script_size', models.BigIntegerField(default=0)),
                ('image_size', models.BigIntegerField(default=0)),
                ('font_size', models.BigIntegerField(default=0)),
                ('other_size', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pageweight.run', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-total_transfer_size'],
                'unique_together': {('run', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('resource_type', models.CharField(max_length=20, verbose_name='Type')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('transfer_size', models.BigIntegerField(default=0, verbose_name='Transfer size (bytes)')),
                ('resource_size', models.BigIntegerField(default=0, verbose_name='Resource size (bytes)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pageweight.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'indexes': [models.Index(fields=['page', 'resource_type'], name='pw_resource_page_type_idx'), models.Index(fields=['page', 'transfer_size'], name='pw_resource_page_xfer_idx')],
            },
        ),
    ]
