# Generated by Django 6.0.5 on 2026-06-02 18:41

import django.db.models.deletion
import django_extensions.db.fields
import lighthouse.models.page
import sites.models.base_job
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDefinition',
            fields=[
                ('audit_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Audit ID')),
                ('category_id', models.CharField(db_index=True, max_length=50, verbose_name='Category ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Audit Definition',
                'verbose_name_plural': 'Audit Definitions',
                'ordering': ['category_id', 'audit_id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url_source', models.CharField(choices=[('sitemap_url', 'Sitemap URL'), ('sitemap_file', 'Sitemap file'), ('url_list', 'URL list')], default='sitemap_url', max_length=20, verbose_name='URL source')),
                ('url_value', models.TextField(blank=True, help_text='Sitemap URL, or newline-separated list of URLs when source is "URL list". Leave blank when using an uploaded sitemap file.', verbose_name='URL value')),
                ('sitemap_file', models.FileField(blank=True, help_text="Uploaded sitemap XML. Only used when source is 'Sitemap file'.", null=True, upload_to=sites.models.base_job.sitemap_path, verbose_name='Sitemap file')),
                ('environment', models.CharField(blank=True, choices=[('local', 'Local'), ('staging', 'Staging'), ('production', 'Production')], help_text='Where this Job runs — tags all Runs for filtering.', max_length=20, verbose_name='Environment')),
                ('crontab', models.CharField(blank=True, help_text='Cron schedule, e.g. "0 9 * * 1" for Monday at 09:00. Leave blank for manual-only Jobs.', max_length=100, validators=[sites.models.base_job.validate_crontab], verbose_name='Crontab')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('last_run', models.DateTimeField(blank=True, help_text='Updated automatically when a Run is created.', null=True, verbose_name='Last run')),
                ('platform', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10, verbose_name='Platform')),
                ('cat_performance', models.BooleanField(default=True, verbose_name='Performance')),
                ('cat_accessibility', models.BooleanField(default=True, verbose_name='Accessibility')),
                ('cat_best_practices', models.BooleanField(default=True, verbose_name='Best practices')),
                ('cat_seo', models.BooleanField(default=True, verbose_name='SEO')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_jobs', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Lighthouse Job',
                'verbose_name_plural': 'Lighthouse Jobs',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('page_count', models.IntegerField(blank=True, help_text='Populated on completion.', null=True, verbose_name='Page count')),
                ('config_file', models.CharField(blank=True, max_length=500, verbose_name='Config file')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='lighthouse.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('report', models.FileField(blank=True, help_text='Raw Lighthouse JSON report; pruned after 90 days.', null=True, upload_to=lighthouse.models.page.audit_report_path, verbose_name='Report')),
                ('html_report', models.FileField(blank=True, help_text='Self-contained Lighthouse HTML report.', null=True, upload_to=lighthouse.models.page.audit_report_path, verbose_name='HTML Report')),
                ('audited', models.BooleanField(default=False, help_text='True when the audit completed without errors or warnings.', verbose_name='Audited')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='lighthouse.run', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'unique_together': {('run', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('rating', models.CharField(blank=True, choices=[('poor', 'Poor'), ('needs-improvement', 'Needs Improvement'), ('good', 'Good')], max_length=20, null=True, verbose_name='Rating')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Value')),
                ('units', models.CharField(blank=True, max_length=50, verbose_name='Units')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_audits', to='lighthouse.auditdefinition', verbose_name='Audit')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='lighthouse.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Audit',
                'verbose_name_plural': 'Page Audits',
                'indexes': [models.Index(fields=['audit', 'rating'], name='lh_pageaudit_audit_rating_idx')],
                'unique_together': {('page', 'audit')},
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, verbose_name='Category ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('needs-improvement', 'Needs Improvement'), ('good', 'Good')], max_length=20, verbose_name='Rating')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='lighthouse.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Category',
                'verbose_name_plural': 'Page Categories',
                'indexes': [models.Index(fields=['category_id', 'score'], name='lh_pagecat_cat_score_idx'), models.Index(fields=['category_id', 'rating'], name='lh_pagecat_cat_rating_idx')],
                'unique_together': {('page', 'category_id')},
            },
        ),
    ]
