# Generated by Django 6.0.5 on 2026-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Optional URL to POST to when the snapshot completes', verbose_name='Webhook URL'),
        ),
    ]
